### ISSUE TITLE
点击太快

### ISSUE THREAD

**Issue by 4what2do** [ImmortalZ/TransitionHelper#15]
java.lang.NullPointerException
                                                                           at immortalz.me.library.TransitionsHeleper$3.run(TransitionsHeleper.java:222)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by ImmortalZ** [comment]
问题已经修复，可以看下最新的版本还有没有这种问题
